// function to generate markdown for README
function generateMarkdown(data) {

    //based on the license that user select, a license badge with link will be added
    let license = " ";
    if (data.license === "MIT") {
        data.license = "[![MIT license](https://img.shields.io/badge/License-MIT-blue.svg)](https://choosealicense.com/licenses/mit/)";
    } else if (data.license === "ISC") {
        license = "[![License: ISC](https://img.shields.io/badge/License-ISC-blue.svg)](https://opensource.org/licenses/ISC)";
    } else if (data.license === "GNU GPLv3") {
        license = "[![License: GPL v3](https://img.shields.io/badge/License-GPLv3-blue.svg)](https://www.gnu.org/licenses/gpl-3.0)";
    } else if (data.license === "Apache-2.0") {
        license = "[![License](https://img.shields.io/badge/License-Apache%202.0-blue.svg)](https://opensource.org/licenses/Apache-2.0)";
    } else if (data.license === "BSD-3-Clause") {
        license = "[![License](https://img.shields.io/badge/License-BSD%203--Clause-blue.svg)](https://opensource.org/licenses/BSD-3-Clause)";
    }
    return `# ${data.title}
  ![badge](https://img.shields.io/badge/license-${data.license}-blue)<br/>

  ${data.license}

## Table of Contents
- [Description](#description)
- [Installation](#installation)
- [Usage](#usage)
- [License](#license)
- [Contributing](#contributing)
- [Tests](#tests)
- [Questions](#questions)

## Description
${data.description}

## Installation
${data.installation}

## Usage
${data.usage}

## License
![badge](https://img.shields.io/badge/license-${data.license}-blue)
${data.license}
<br/>
This application is covered under ${data.license} license. 

## Contributing
Contributors: ${data.contributing}.
Please read this [Setting guidelines for repository contributors](https://docs.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors) for more informations.

## Tests
${data.tests}

## Questions

Please direct contact me with any questions: 
Email: ${data.email}<br/><br />
GitHub:  [${data.username}](https://github.com/${data.username})

This README was generated by [README-generator](https://github.com/wendyVo/ReadMe-generator)_
`;
}

module.exports = generateMarkdown;